Repository 2024-CMPU9010-GROUP-3/magpie, pull requests merged in 2024-09, with the labels that each got.

#17 Adds base setup for backend
  Backend/Dockerfile
  Backend/cmd/main/main.go
  Backend/go.mod
  Backend/internal/routes/routes.go
  Backend/readme.md
Labels: enhancement

#19 Setup/frontend
  .gitignore
  Frontend/.gitignore
  Frontend/components.json
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/app/about/page.tsx
  Frontend/src/app/components/about/AboutPage.tsx
  Frontend/src/app/components/home/HomePage.tsx
  Frontend/src/app/favicon.ico
  Frontend/src/app/fonts/GeistMonoVF.woff
  Frontend/src/app/fonts/GeistVF.woff
  Frontend/src/app/globals.css
  Frontend/src/app/layout.tsx
  Frontend/src/app/page.tsx
  Frontend/src/components/ui/button.tsx
  Frontend/src/lib/utils.ts
  Frontend/tailwind.config.ts
Labels: enhancement

#20 Add powerpoint
  Documentation/presentation/presentation1/powerpoint.tex
Labels: documentation

#27 Misc/student-id
  .github/Members/C19349793.md
  .github/Members/template.md
Labels: documentation

#28 Misc/ci-cd-first-revision
  .github/WORKFLOWS/backend-test.yaml
  .github/WORKFLOWS/branch-name-test.yaml
Labels: enhancement

#22 Add middleware support to backend
  Backend/cmd/main/main.go
  Backend/internal/middleware/logging.go
  Backend/internal/middleware/middleware.go
  Backend/readme.md
Labels: enhancement

#32 add student id
  .github/Members/D23124588.md
Labels: documentation

#35 Misc/student
  .github/Members/D23124940.md
Labels: documentation

#50 Adjusts indentation
  .github/workflows/backend-test.yaml
Labels: bug

#56 Remove package.json from main
  package.json
Labels: bug

#61 Frontend/map-marker
  Frontend/package.json
  Frontend/src/app/components/map/MapboxMap.tsx
  Frontend/src/components/ui/floating-dock.tsx
  Frontend/src/components/ui/input.tsx
  Frontend/src/lib/interfaces/types.tsx
Labels: enhancement

#70 Backend/split backend buildtags
  .github/workflows/backend-private-test.yaml
  .github/workflows/backend-public-test.yaml
  Backend/.version
  Backend/Dockerfile.private
  Backend/Dockerfile.public
  Backend/cmd/main/main.go
  Backend/go.mod
  Backend/internal/handlers/auth_public.go
  Backend/internal/handlers/handlers.go
  Backend/internal/handlers/points_private.go
  Backend/internal/handlers/points_public.go
  Backend/internal/middleware/logging.go
  Backend/internal/middleware/middleware.go
  Backend/internal/routes/routes.go
  Backend/internal/routes/routes_private.go
  Backend/internal/routes/routes_public.go
  Backend/internal/util/util.go
  Backend/private/readme.md
  Backend/public/cmd/main/main.go
  Backend/public/go.mod
  Backend/public/internal/handlers/handlers.go
  Backend/public/internal/handlers/points.go
  Backend/public/internal/middleware/logging.go
  Backend/public/internal/middleware/middleware.go
  Backend/public/internal/util/util.go
  Backend/readme.md
  Backend/routes-private.md
  Backend/routes-public.md
Labels: enhancement

#71 Misc/ci-frontend-build
  .github/workflows/frontend-build.yaml
  .gitignore
Labels: enhancement
